# Generated by Django 3.1.3 on 2020-11-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_model', models.CharField(max_length=25)),
                ('price', models.PositiveIntegerField()),
                ('screen_size', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=25)),
                ('memory', models.PositiveIntegerField()),
                ('battery_capacity', models.PositiveIntegerField()),
                ('picture', models.ImageField(upload_to='phones')),
            ],
        ),
    ]
