# Generated by Django 3.1.3 on 2020-11-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='brand',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
