# Generated by Django 3.1.3 on 2020-11-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phone_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='phone_model',
        ),
    ]
