# Generated by Django 3.1.3 on 2020-12-01 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('phones', '0005_phone_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
