# Generated by Django 3.1.3 on 2020-12-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_auto_20201201_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='user',
            new_name='owner',
        ),
    ]
