# Generated by Django 3.1.3 on 2020-12-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0008_auto_20201211_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='picture',
            field=models.ImageField(default='', upload_to='phones'),
            preserve_default=False,
        ),
    ]
