# Generated by Django 3.1.3 on 2020-12-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0009_phone_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='condition',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
