# Generated by Django 3.1.3 on 2020-12-11 15:26

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0011_phone_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='telephone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
