# Generated by Django 3.1.3 on 2020-12-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0013_remove_phone_telephone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='capacity',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
